### ISSUE TITLE
Seems down atm with internal server errors 500

### ISSUE THREAD

**Issue by simonanez** [OMSCentral/omscentral#76]
When selecting any course
![image](https://user-images.githubusercontent.com/13173655/107600261-3414c980-6bf1-11eb-8a6b-93a06b490263.png)

**Comment by mehmetbajin** [comment]
@simonanez I am unable to reproduce.

Could you try clearing your browser cache for omscentral.com? Or trying in Private mode?

**Comment by mehmetbajin** [comment]
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/10424048/107638474-a57a6980-6c3d-11eb-958c-6c8b54be440c.png">

^ From last 24 hours...

**Comment by mehmetbajin** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/10424048/107638584-c478fb80-6c3d-11eb-8b19-7ac4572a7fd8.png">

I think root cause is an old client build. I rolled out a backwards-incompatible change last week, and we're seeing the pains from that. In the future, a more gradual rollout plan should address the problem.
